name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:
      ACTION_SECRET: ${{ secrets.ACTION_SECRET }}
    steps:
      - run: echo $GITHUB_RUN_ID
      - run: echo $ACTION_SECRET
      - run: echo $GITHUB_ACTION
      - run: echo $GITHUB_RUN_NUMBER
      - run: ls
      - run: cd ./test && ls
