name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_RUN_ID
      - run: echo $GITHUB_ACTION
      - run: echo $GITHUB_RUN_NUMBER
